### ISSUE TITLE
Some UI observations

### ISSUE THREAD

**Issue by ypxk** [dndrks/cheat_codes_2#10]
(i recognize this is all super opinionated so take it or leave it, obviously.)

the old and new pages seem slightly incongruous with each other UI wise, trying to examine why: 

global: 

1. since enc2 is our dedicated “scroller” for navigating the main menu, it feels like it wants to be the scroller to navigate sub menus, but i see why that doesn't work. maybe add enc1 as a navigation option for the main menu?

2. on the new pages, where k3 does more menu diving, it feels bad to get “stuck” in the deepest level of menu by pressing k3. pressing a button that did something previously and having nothing happen makes it feel as though maybe something is wrong with the script, or something has changed that you failed to perceive. it feels like k3 wants to send you back to the first layer of the menu of the current page when you’ve reached the end, the way it does in the earlier pages (loops,levels,pans,filters).  

for example, on the delay page: does it make sense to have k3 loop through the sections rather than "arrive" at the lowest level of menu? maybe it's more important to know you've reached the end, i don't know. i get tripped up on it a little! 

euclid page: i think when you hold key 1 and see “1,2,3” mode you might mean “a, b, c” mode? i always trip over myself trying to differentiate between the buffers and the banks--i thought the letters were how to differentiate? (i am probably just confused, i just realized the 1,2,3 naming convention is also used on rnd)

random page: 
1. it would be cool if “k1+k3 to activate” worked regardless of what on the screen is highlighted  
2. it's weird that enc1 scrolls between the banks, but then, after pressing k3 to advance, does nothing. i get the logic––enc1 is for scrolling, enc2/3 reserved for changing params), but the hand movement required is sort of awkward. it seems fine to just interpret the random generator object number as a list that you "scroll" through with enc1, even though not all other numbers are visible at all times.  
3. (this is another one where it feels like maybe k3 should loop between the three sections?) 

(pretty smooth session tonight! i have occasionally seen a bank switch itself into arp mode without being told to, and have observed the focus mode not properly play with euclidian, delay, filter menus but cannot even come close to reproducing them so not going to report at this time)

**Comment by dndrks** [comment]
yo, @ypxk , absolutely fantastic and super helpful reflections -- thank you!!

addressed some major usability speedbumps with #11 

roadmap:
- [x] delays:
     - e1 should always swap between L and R
     - menu should start with `ctl` highlighted
     - k3 should cycle between the top-layer menus and the parameters under them
     - e2 should select across the top or bottom layer
     - e3 should edit the parameter
- [x] loops:
     - e1 should navigate between lanes (currently k3 presses)
     - k1+e1 can reveal the window movement option
     - k3 on a lane will swap just that lane to the alt menu
     - on the alt menu, e2 and e3 will adjust params with k1+e1 to change pads

thank you so so much for the help rubber-ducking this -- i really appreciate it 💞

**Comment by dndrks** [comment]
(note to self: add looping indicator on [loops] page)

**Comment by dndrks** [comment]
completed [loops] roadmap in #17

**Comment by dndrks** [comment]
completed [delays] roadmap in #18 !! please let me know how these changes feel, especially if they do not feel good, but I think we've tackled everything from your super excellent notes!!!
