### ISSUE TITLE
Auto Chop sets clip to sample buffer#1

### ISSUE THREAD

**Issue by DuellingAnts** [dndrks/cheat_codes_2#15]
I load up 3 samples, one on each bank A, B and C. 
I click alt+clip on each bank, and alt+slot 1,2 or 3 to select the same sample to all pads in that bank.

Issue: If I click alt+auto chop the bank automatically sets all samples to clip slot 1

**Comment by dndrks** [comment]
hey hey! sorry, this is an undocumented change!

auto-chop is now in zilchmo 4: `[ ][x][ ][ ]`
if you alt+auto-chop, it will re-calculate the start/end point of every pad to be 1/16th of the length of the assigned buffer (live or clip).

known bug, but for now all pads need to be set to the same buffer/clip to do this. later tonight, will release a fix :)

**Comment by dndrks** [comment]
note to self: figure out whether `* (pad.pad_id-1)))+((pad.clip-1)*8)` needs to be added to any of the `if pad.mode == 1 and pad.clip == rec.clip then` zilchno statements

**Comment by DuellingAnts** [comment]
ah, cool !

**Comment by dndrks** [comment]
fixed in #17
