### ISSUE TITLE
sample loading error

### ISSUE THREAD

**Issue by andr-ew** [dndrks/cheat_codes_2#16]
maybe u know this already but I just booted up the beta for the first time and it doesn't look like clip sample load is working 
¯\_(ツ)_/¯  seems to be going fine in cheat codes 1 with the same files.

I get this error on the param action

```
lua: /home/we/norns/lua/core/softcut.lua:297: error: requires 3 arguments
stack traceback:
        [C]: in field 'cut_buffer_clear_region_channel'
        /home/we/norns/lua/core/softcut.lua:297: in function 'core/softcut.buffer_clear_
region_channel'
        /home/we/dust/code/and_cc/cheat_codes.lua:2437: in global 'load_sample'
        /home/we/dust/code/and_cc/lib/start_up.lua:81: in field 'action'
        /home/we/norns/lua/core/params/file.lua:60: in function 'core/params/file.bang'
        /home/we/norns/lua/core/params/file.lua:35: in function 'core/params/file.set'
        (...tail calls...)
        /home/we/norns/lua/core/menu/params.lua:267: in function 'fileselect.callback'
        /home/we/norns/lua/lib/fileselect.lua:50: in function 'fileselect.exit'
        /home/we/norns/lua/lib/fileselect.lua:133: in function 'fileselect.key'
        /home/we/norns/lua/core/menu.lua:139: in function </home/we/norns/lua/core/menu.
lua:116>
```

doesn't look like buffer clear function is happy with your args !

**Comment by dndrks** [comment]
?? weird. are you on a non-release norns build or the perhaps the dev branch? nobody’s brought this up and i haven’t seen anything like this across testing on a few devices. :/

edit: woop! didn't mean to close the issue. re-opened :)

**Comment by andr-ew** [comment]
ah - yes i'm on my slight fork which is synced with norns/main (which i think has softcut changes ?)

i can try in my other norns after i put it back together hehe

**Comment by dndrks** [comment]
ah, yeah i’m testing with release builds only. lmk, good to have an eye
toward the future (but also sorta unsure why a three argument call wouldn’t
register as having three arguments)! thanks andrew!

**Comment by dndrks** [comment]
oh also if you’re starting testing, the most recent changes are here :
https://github.com/dndrks/cheat_codes2-beta/tree/loops-ui

i’ll merge it all in soon, but figured if you’re putting time into any
pre-release playing, there are a lot of fixes and changes in that branch

thank you!

**Comment by andr-ew** [comment]
cool so force update seemed to do it, good catch, and watch out for the next release !
