### ISSUE TITLE
CC Beta 4 K1 button sporadically responding to go back and forth from Norns main screens to cheat codes

### ISSUE THREAD

**Issue by Quasimonastic** [dndrks/cheat_codes_2#21]
Issue:
CC Beta 4 loads perfectly but K1 is very sporadic in getting back to the Norns interface to edit CC Prams, make selections etc. Sporadic = Sometimes it works with a very quick double tap other times it’s a single tap and other times neither. This is the first beta that I’ve had this issue.

**Comment by dndrks** [comment]
hey hey! thanks for the ping on the GH :)

reducing the k1 hold time overrides your muscle memory for sure. it’s set
to 100ms, usually 500ms. i think the results are much more playable within
the script, but it does create a cognitive dissonance when getting used to
it for the top-level menu access.

i guess the big q is whether you like the responsiveness in-script, then
maybe the next would be would you rather tune this yourself? i can expose a
param for k1 hold time and you can just dial it in to what might feel best?

lemme know! open to other ideas as well!

**Comment by Quasimonastic** [comment]
Dan,
Now that I know it's not a bug I can deal with it for sure. I'm only guessing but I think others will have trouble too since it seems like all the other Norns scripts I've tried (which isn't many) seem set at 500ms. I'm sure you will be noting the change in the manual but it does make some sense to have a K1 param exposed if it indeed drives some people nuts lol!

**Comment by dndrks** [comment]
for sure, apologies for the surprise! also, just struck by an idea
(@CarlosUnch / @Quasi / @mbutz): maybe k1 hold should be normal on main
menu, 100ms inside any of the individual pages, 10ms on the delay jump
param?

**Comment by Quasimonastic** [comment]
I like that idea but having no UX experience I don't know if that would get more confusing. Cheat codes is so deep anyway that if it's all documented I can see it going over well.
