### ISSUE TITLE
Random Pattern Functionality

### ISSUE THREAD

**Issue by mbutz** [dndrks/cheat_codes_2#22]
See: https://llllllll.co/t/codebreaking-cheat-codes-livestreams-sun-aug-16-11-12-15p-edt/31717/198

Version: `cheat_codes2-beta-beta3-hotfix`

Once a random pattern is created (via Norns menu)I, if it is stopped, after some time the pattern (the prevously recorded? the recent random?) plays again automatically. The only way to stop the pattern is to delete it (alt + pattern grid key).

I would expect something like that:

* recorded patterns persist until the are deleted and can be started/stopped with the pattern grid key
* a random pattern overwrites a manually recorded one
* random patterns can be created by pushing alt + r button (according to settings via Norns menu)
* as the pattern key lights up I assume I can use this to stop the random pattern (does not seem to work)

**Comment by dndrks** [comment]
hey hey! thanks for logging this here :)

i'm having a bit of trouble repro'ing this issue as described on [beta 4](https://github.com/dndrks/cheat_codes2-beta/releases/tag/beta4) -- here's how I tested with a grid plugged in:

- rec mode: distro as well as loose
- quantize: off as well as on
- rand pat 1 style: rand as well as horizontal
- rand pat 1 note length: rand as well as 1/16th
- create a random pattern through the `rand pat [K3]` [timing] menu
- random pattern begins
- stop (but don't clear) the pattern with either the grid pattern key or K1 hold on the pattern's [timing] menu
- pattern did not restart

the only thing I can think of is that maybe a meta sequencer pattern was running in the background? i've caught myself up with that a few times -- happy to investigate with more info, tho!!

**Comment by mbutz** [comment]
I will check again and try to describe a reproducible case (if there is still anything to report). I am not sure when this can be, just that you know, I am still on it...

**Comment by mbutz** [comment]
Hi, I can't reproduce this either. So sorry for the confusion. I'll close this.
