### ISSUE TITLE
Midi channel selection odd behavior.

### ISSUE THREAD

**Issue by Quasimonastic** [dndrks/cheat_codes_2#33]
Hi Dan,

This was found on release candidate 2 but I checked and it was happening in the other beta releases as well. Under the Midi Keyboard setup/ BankA, B, and C pad channels. Issue: When turning encoder 3 to select a channel the numbers do not react smoothly. As in going contiguously from 1 to 16. Rather they sporadically skip numbers until 16 is reached. On top of that, let's say you start at 1 turn a tiny amount and get skipped from 2 to 5, 6 then stop at 8. If I turn the knob back (to get back to 1) the numbers keep incrementing. Because I have to switch channels for the Midi fighter to work, I know if I can get to 7 then turn the dial back I can get to 9 in a few tries. But I can never get to 9 turning the dial clockwise. I'm using the latest Norns shield if that matters.

Hope this helps!
Paul

**Comment by dndrks** [comment]
hey paul! thanks for the report.

hmmm. not seeing this on my side -- what are your other `MIDI keyboard setup` PARAMS settings in the same submenu?

**Comment by Quasimonastic** [comment]
Hi Dan, they are:

enable midid control = yes
midi control device = port 2
enable midi echo = yes
Bank a pad channel = 1
Bank b pad channel = 2
Bank c pad channel = 9
bank a, b, and c pad midi base = 53

As a reference I checked the original cheat codes and all numbers changed by E3 work perfectly. Also in this release #2 I don’t get the error anywhere else.

P

**Comment by dndrks** [comment]
thank you for the info! still not seeing it here. is maiden printing any errors?

**Comment by Quasimonastic** [comment]
Maiden didn’t print an error when I was setting back c to channel 9. But I noticed in the maiden panel that persistent save is being called but every time I load CC the midi info is not saved and I have to re-input it for every session. Then I thought maybe I have to save a session with Pset so I did that, loaded the normal CC then loaded release candidate 2 again and got the output below. I restarted my shield and when I loaded CCR2 it worked but my midid setting were gone. I went to pset/load and had to press K3 a few times but it loaded my previous session and had the midi settings remained where I had set them (per my previous email).

I say all this not knowing if these are connected problems. If this opens up a can of worms, I’m fine with it being local to me :)


matron
sc
# script load: /home/we/dust/code/cheat_codes2-beta-rc-2/cheat_codes.lua

### cleanup failed with error: /home/we/dust/code/cheat_codes2-beta-rc-2/cheat_codes.lua:4568: attempt to concatenate a nil value (local 'coll')
# script clear

ERROR (i2c/hp) failed to write

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/cc_pattern_time.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/help_menus.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/main_menu.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/encoder_actions.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/arc_actions.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/zilchmos.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/start_up.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/grid_actions.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/easing.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/midicheat.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/arp_actions.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/rnd_actions.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/cc_musicutil.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/delay.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/euclid.lua

including /home/we/dust/code/cheat_codes2-beta-rc-2/lib/midicheat.lua

pset >> write: /home/we/dust/data/system.pset

# script run

>> reading PMAP /home/we/dust/data/cheat_codes2-beta-rc-2/cheat_codes/cheat_codes.pmap

Engine.register_commands; count: 0
___ engine commands ___

___ polls ___

amp_in_l
amp_in_r

amp_out_l
amp_out_r
cpu_avg

cpu_peak
pitch_in_l

pitch_in_r

# script init

pset >> read: /home/we/dust/data/cheat_codes2-beta-rc-2/cheat_codes/cheat_codes-01.pset

### SCRIPT ERROR: init

attempt to compare string with number
stack traceback:
	/home/we/norns/lua/core/norns.lua:136: in function </home/we/norns/lua/core/norns.lua:136>
	[C]: in function 'math.max'
	/home/we/norns/lua/lib/util.lua:102: in function 'util.clamp'
	/home/we/norns/lua/core/params/number.lua:39: in function 'core/params/number.set'
	/home/we/norns/lua/core/paramset.lua:395: in function 'core/paramset.read'
	/home/we/norns/lua/core/paramset.lua:408: in function 'core/paramset.default'
	/home/we/dust/code/cheat_codes2-beta-rc-2/cheat_codes.lua:880: in global 'init'
	/home/we/norns/lua/core/script.lua:105: in function 'core/script.init'
	[C]: in function 'xpcall'
	/home/we/norns/lua/core/norns.lua:137: in field 'try'
	/home/we/norns/lua/core/engine.lua:91: in function </home/we/norns/lua/core/engine.lua:89>

**Comment by dndrks** [comment]
hey hey! hope all's well :)

this might've just become moot with the native MFT mapping, but lmk if this is still a problem with the release! <3
