### ISSUE TITLE
bug in tracker.lua

### ISSUE THREAD

**Issue by jaseknighter** [dndrks/cheat_codes_2#47]
this just popped up in the lua code checker i have in visual studio...so i haven't actually replicated this issue.

line 120 of tracker.lua references the get_tick function when it should be calling the function (i.e. a `()` is missing).

so... `self:set_tick(self:get_tick + 1)` should be changed to... `self:set_tick(self:get_tick() + 1)`

**Comment by dndrks** [comment]
thanks so much for the eyes, jonathan!
tracker is old / dead code, unused by the script, so will remove it
tomorrow! 🌈✨

**Comment by dndrks** [comment]
dang, tomorrow sure took a long time! removed :)))) tytyty for looking out!!
