### ISSUE TITLE
arp skipping first note on retrigger

### ISSUE THREAD

**Issue by edisonSF** [dndrks/cheat_codes_2#9]
not sure if this is just how im using the arp... 
but when i (grid) 
turn on arp, hold down a pad, press arp again....
record pad presses and they loop.... 
stop arp
start arp
it skips the first pad and places it at the end of the sequence?

holler!

**Comment by dndrks** [comment]
oh GOOD catch!!! i got it fixed locally, will push an update tonite <3

**Comment by edisonSF** [comment]
oh snap! forgot to label this... sorry... just signed up for github

**Comment by dndrks** [comment]
nahhh you’re great, a hero :) thanks for engaging in the process here —
really helpful for keeping the task list in check!

**Comment by dndrks** [comment]
fixed with #11
